---
- name: Create .ssh directory for edxapp
  file:
    path: "{{ edxapp_data_dir }}/.ssh"
    state: directory
    owner: "root"
    group: "root"
    recurse: yes
  become_method: sudo
  become: no
  become_user: "root"

- name: Check if git private key ( ~/.ssh/id_rsa_git ) exists
  stat:
    path: "{{ git_ssh_key }}"
  register: git_st

- debug: msg="{{ git_ssh_key }}"
- debug: msg="{{ git_st }}"

- name: Deploy git SSH private key for edxapp
  copy:
    src: "{{ git_ssh_key }}"
    dest: "{{ edxapp_data_dir }}/.ssh/id_rsa"
    remote_src: true
    owner: "root"
    group: "root"
    mode: 0600
    force: yes
  become_method: sudo
  become: no
  become_user: "root"
  when: git_st.stat.exists
